name: Draft Pre-Release

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        prerelease: true
        artifact: "build" # Output path of Go build from the Merge Master workflow
        body: |
          # Release
          
          ## Features
          - here
          
          ## Fixes
        
        token: ${{ secrets.GITHUB_TOKEN }}
