name: Tag Merge to Master
on:
  push:
    branches:
    - master

jobs:
  tag:
    name: Bump semantic version
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: [1.12.x, 1.13.x]
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Print GITHUB_REF
      run: echo ${GITHUB_REF}
    
    - uses: olegtarasov/get-tag@v2
      id: tagName
#         with:
#           tagRegex: "foobar-(.*)"  # Optional. Returns specified group text as tag name. Full tag string is returned if regex is not defined.
#           tagRegexGroup: 1 # Optional. Default is 1.

    - name: Some other step # Output usage example
      run: echo ${{ steps.tagName.outputs.tag }}
    
    - name: Get the version
      id: tag
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    
    - name: Print Tag
      run: echo $VERSION
    
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -o build/terrain-${{ matrix.os }}-${{ steps.outputs.tag.result }} ./cmd/terrain

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ncipollo/release-action@v1
      with:
        draft: true
        prerelease: true
        artifact: "build" # Output path of Go build from the Merge Master workflow
        body: |
          # Release
          
          ## Features
          - here
          
          ## Fixes
        
        token: ${{ secrets.GITHUB_TOKEN }}
