name: Tag Merge to Master
on:
  push:
    branches:
    - master

jobs:
  tag:
    name: Bump semantic version
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch

  build:
    name: Build
    needs: [tag]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        go: [1.12.x, 1.13.x]
    steps:
    - name: Set up Go ${{ matrix.go }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - name: Check out code into the Go module directory
      id: checkout
      uses: actions/checkout@v2
    
    # Because the GITHUB_REF will be refs/heads/master,
    # We need to get the tag for the current commit
    # git describe --tags
    - name: Get the version
      id: tag
      shell: bash
      run: |
        git pull
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        echo ::set-output name=result::$(git describe --tags)
    
    - name: Print Tag
      shell: bash
      run: echo ${{ steps.tag.outputs.result }}
    
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Get dependencies
      shell: bash
      run: |
        go get -v -d ./...

    - name: Build
      shell: bash
      env:
        OS: ${{ runner.os }}
        TAG: ${{ steps.tag.outputs.result }}
      run: |
        OS=$(echo $OS | tr [A-Z] [a-z])
        go build -v -o build/terrain-${OS}-${TAG} ./cmd/terrain
    
    - name: Archive build artifacts
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build

  container:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    # Because the GITHUB_REF will be refs/heads/master,
    # We need to get the tag for the current commit
    # git describe --tags
    - name: Get the version
      id: tag
      shell: bash
      run: |
        git pull
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        echo ::set-output name=result::$(git describe --tags)

    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build
        path: build

    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: nicklarsennz/terrain
        username: nicklarsennz
        password: ${{ secrets.DOCKERHUB_SECRET }}

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2

    # Because the GITHUB_REF will be refs/heads/master,
    # We need to get the tag for the current commit
    # git describe --tags
    - name: Get the version
      id: tag
      shell: bash
      run: |
        git pull
        git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        echo ::set-output name=result::$(git describe --tags)

    - name: Download build artifacts
      uses: actions/download-artifact@v1
      with:
        name: build
        path: build

    - name: Check something
      shell: bash
      run: ls -al

    - uses: ncipollo/release-action@v1
      with:
        tag: ${{ steps.tag.outputs.result }}
        draft: true
        prerelease: true
        artifacts: "build/*" # Output path of Go build from the Merge Master workflow
        body: |
          # Release
          
          ## Features
          - here
          
          ## Fixes
          - here
        
        token: ${{ secrets.GITHUB_TOKEN }}
