name: Tag Merge to Master
on:
  push:
    branches:
    - master

jobs:
  tag:
    name: Bump semantic version
    runs-on: [ubuntu-latest]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: patch
